version: '3.8'
services:
  backend-deal-service:
    build:
      context: ./backend/deal-service
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: ./backend/deal-service
          target: /app
  celery-worker:
    build:
      context: ./backend/deal-service
      dockerfile: Dockerfile.celery
    develop:
      watch:
        - action: sync
          path: ./backend/deal-service
          target: /app
    depends_on:
      - backend-deal-service
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
      