version: '3.8'
services:
  backend-deal-service:
    build:
      context: ./backend/deal-service
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: ./backend/deal-service
          target: /app
    depends_on:
      - redis
      - selenium-hub
      - celery-worker
  celery-worker:
    build:
      context: ./backend/deal-service
      dockerfile: Dockerfile.celery
    develop:
      watch:
        - action: sync
          path: ./backend/deal-service
          target: /app
    depends_on:
      - redis
      - selenium-hub
  flower:
    build:
      context: ./backend/deal-service
      dockerfile: Dockerfile.flower
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery-worker
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  selenium-hub:
    image: selenium/hub:4.13.0
    ports:
      - 4442:4442
      - 4443:4443
      - 4444:4444
    environment:
      GRID_MAX_SESSION: 8     
  selenium-chrome_node_1:
    image: selenium/node-chrome:4.13.0
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_STEREOTYPE: "{\"browserName\":\"chrome\",\"browserVersion\":\"117\",\"platformName\": \"Windows 10\"}"
  frontend-webapp:
    build:
      context: ./frontend/webapp
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    develop:
      watch:
        - action: sync
          path: ./frontend/webapp
          target: /app
          ignore: 
            - node_modules
        - action: rebuild
          path: ./frontend/webapp/package.json
    depends_on:
      - backend-deal-service
