version: '3.8'
services:
  backend-deal-service:
    build:
      context: ./backend/deal-service
      dockerfile: Dockerfile.deploy
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8000/flask-health-check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: always
  celery-worker:
    build:
      context: ./backend/deal-service
      dockerfile: Dockerfile.celery
    depends_on:
      - backend-deal-service
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  selenium-chrome:
    build:
      context: ./backend/deal-service
      dockerfile: Dockerfile.selenium
    ports:
      - "4444:4444"
    shm_size: '2g'
  nginx-proxy:
    build: ./backend/nginx
    restart: always
    volumes:
      - ./backend/nginx/default.conf:/tmp/default.conf
    environment: 
      - FLASK_SERVER_ADDR=backend-deal-service:8000
    ports:
      - "80:80"
    depends_on:
      - backend-deal-service
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:80/health-check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    command: /app/start.sh
