version: '3.8'
services:
  web-app:
    image: bokuan/veekly-bobangs-clockbox:latest
    ports:
      - "3001:3001"
  env_file:
    - ./frontend/webapp/.env.local
  nginx-web-app:
    build: ./frontend/nginx
    restart: always
    volumes:
      - ./frontend/nginx/default.conf:/tmp/default.conf
    environment: 
      - WEB_APP_ADDR=web-app:3001
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web-app
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:80/health-check || exit 1"]
      interval: 1000s
      timeout: 10s
      retries: 3
    command: /app/start.sh
