version: '3.8'
services:
  backend-deal-service:
    build:
      context: ./backend/deal-service
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: ./backend/deal-service
          target: /app
  celery-worker:
    build:
      context: ./backend/deal-service
      dockerfile: Dockerfile.celery
    develop:
      watch:
        - action: sync
          path: ./backend/deal-service
          target: /app
    depends_on:
      - backend-deal-service
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  selenium-chrome:
    build:
      context: ./backend/deal-service
      dockerfile: Dockerfile.selenium
    ports:
      - "4444:4444"
    shm_size: '2g'
  frontend-webapp:
    build:
      context: ./frontend/webapp
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    develop:
      watch:
        - action: sync
          path: ./frontend/webapp
          target: /app
        - action: rebuild
          path: ./frontend/webapp/package.json
    depends_on:
      - backend-deal-service
