version: '3.8'
services:
  web-app:
    image: bokuan/veekly-bobangs-clockbox:latest
    ports:
      - "3001:3001"
    environment:
      - API_URL=http://192.168.1.203:8000
      - EMAIL_REDIR_URL=https://weekly-lobangs.mooo.com
  nginx-web-app:
    build: ./frontend/nginx
    restart: always
    volumes:
      - ./frontend/nginx/default.conf:/tmp/default.conf/:ro
      - ./frontend/certbot/www:/var/www/certbot/:ro
      - ./frontend/certbot/conf/:/etc/nginx/ssl/:ro
    environment: 
      - WEB_APP_ADDR=web-app:3001
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web-app
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:80/health-check || exit 1"]
      interval: 1000s
      timeout: 10s
      retries: 3
    command: /app/start.sh
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./frontend/certbot/www:/var/www/certbot/:rw
      - ./frontend/certbot/conf/:/etc/letsencrypt/:rw
