FROM --platform=linux/amd64 python:3.10-slim-buster

ENV CELERY_BROKER_URL redis://redis:6379/0
ENV CELERY_RESULT_BACKEND redis://redis:6379/0
ENV SELENIUM_URL http://selenium-hub:4444/wd/hub

WORKDIR /app
COPY ./requirements.txt /app
RUN pip install -r requirements.txt
COPY . .
EXPOSE 8000

CMD gunicorn --chdir /app/src --workers 2 --max-requests 1000 --max-requests-jitter 200 -t 65 -b 0.0.0.0:8000 app:app
