FROM --platform=linux/amd64 python:3.10-slim-buster

ENV CELERY_BROKER_URL redis://redis:6379/0
ENV CELERY_RESULT_BACKEND redis://redis:6379/0

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install flower

COPY . .

EXPOSE 5555

WORKDIR /app/src

CMD ["celery", "-A", "app.celery", "flower", "--port=5555"]
