apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-deployment
  labels:
    app: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
        - name: celery
          image: bokuan/veekly-bobangs-celery:latest
          env:
            - name: CELERY_BROKER_URL
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: CELERY_BROKER_URL
            - name: CELERY_RESULT_BACKEND
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: CELERY_RESULT_BACKEND
            - name: SELENIUM_URL
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: SELENIUM_URL
---
apiVersion: v1
kind: Service
metadata:
  name: celery-service
  labels:
    app: celery
spec:
  selector:
    app: celery
  ports:
    - protocol: TCP
      port: 5555  # Dummy port, not actually used
      targetPort: 5555  # Dummy port, not actually used
