name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - main
    paths:
      - 'backend/deal-service/**'
jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
      - name: Run Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/vb-app
            docker-compose -f ./docker-compose.backend-deploy.yml down
            docker-compose -f ./docker-compose.backend-deploy.yml build
            docker-compose -f ./docker-compose.backend-deploy.yml up -d
